### ISSUE TITLE
Problem in inversion of G matrix in order to use in BSLMM

### ISSUE THREAD

**Issue by Siavash-cloud** [YinLiLin/hibayes#14]
Hello,
I applied the BSLMM algorithm to predict genomic breeding values, estimate variance components, and... in hibayes.
This is the script that I used:
`fit <- bayes(y = pheno[, 8], M = geno, model ="BSLMM" , niter = 100000, nburn = 20000,threads=10)`
After running this script, I faced with an error which is:
Error in make_grm(M, lambda = lambda, inverse = TRUE, verbose = verbose) : 
  system is computationally singular: reciprocal condition number = 4.452607e-26,
try to specify parameter 'lambda' with a small value, eg: 0.001 or bigger
I could solve it by adding lambda=0.01 as your software pointed out.
I wonder why when I used other algorithms such as BayesA, BayesCpi and ... I did not face this error? 
Is there any difrences between GRM (genomic relationship matrices) construction and their inversion in different methods?
Also, I wonder how can I solve this problem without giving a lambda value in BSLMM?
Regards,
Siavash

**Comment by YinLiLin** [comment]
Hi Siavash,

Thank you for trying hibayes.
That is because that BSLMM is a method in combination of GBLUP and BayesCpi, the inverse of GRM (genomic relationship matrix) is required to construct MME to obtain the polygenic effect of all markers, which is not involved in other Bayesian methods. Since the GRM is not invertible for some cases due to unexpected reasons, the 'lambda' can help to address this problem. The very small ridge regression value 'labmda' would not significantly affect the estimated results, so no need to wary about it.

Best,
Lilin

**Comment by Siavash-cloud** [comment]
Thanks!
